// <auto-generated />
using System;
using Ananke.Infrastructure.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ananke.Infrastructure.Migrations
{
    [DbContext(typeof(AnankeContext))]
    [Migration("20240929030405_GalleryCreate")]
    partial class GalleryCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ananke.Domain.Entity.Items.Extension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Extensions");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Items.ExtensionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExtensionTypes");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Items.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExtensionId")
                        .HasColumnType("integer");

                    b.Property<int?>("FolderId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionId");

                    b.HasIndex("FolderId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Media.Images.Galleries.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Media.Images.Galleries.GalleryChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GalleryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GalleryId");

                    b.ToTable("GalleryChapters");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Media.Images.Galleries.GalleryChapterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ItemId");

                    b.ToTable("GalleryChapterItems");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Items.Extension", b =>
                {
                    b.HasOne("Ananke.Domain.Entity.Items.ExtensionType", "Type")
                        .WithMany("Extensions")
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Items.Folder", b =>
                {
                    b.HasOne("Ananke.Domain.Entity.Items.Folder", "Parent")
                        .WithMany("Folders")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Items.Item", b =>
                {
                    b.HasOne("Ananke.Domain.Entity.Items.Extension", "Extension")
                        .WithMany("Items")
                        .HasForeignKey("ExtensionId");

                    b.HasOne("Ananke.Domain.Entity.Items.Folder", "Folder")
                        .WithMany("Items")
                        .HasForeignKey("FolderId");

                    b.Navigation("Extension");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Media.Images.Galleries.GalleryChapter", b =>
                {
                    b.HasOne("Ananke.Domain.Entity.Media.Images.Galleries.Gallery", "Gallery")
                        .WithMany("Chapters")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Media.Images.Galleries.GalleryChapterItem", b =>
                {
                    b.HasOne("Ananke.Domain.Entity.Media.Images.Galleries.GalleryChapter", "Chapter")
                        .WithMany("Items")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ananke.Domain.Entity.Items.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Items.Extension", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Items.ExtensionType", b =>
                {
                    b.Navigation("Extensions");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Items.Folder", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Media.Images.Galleries.Gallery", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Ananke.Domain.Entity.Media.Images.Galleries.GalleryChapter", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
